name: pier_pasteleria
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Estado
  provider: ^6.1.0

  # HTTP y API
  http: ^1.2.1

  # Almacenamiento local (JWT)
  shared_preferences: ^2.2.3

  # Navegación
  go_router: ^14.2.7

  # Imágenes de red con caché
  cached_network_image: ^3.3.1

  # Selector de imágenes (perfil, reseñas, reembolsos, evidencia de entrega)
  image_picker: ^1.1.2

  # Abrir marcador / WhatsApp (módulo repartidor)
  url_launcher: ^6.3.0

  # Formatos de fecha y moneda
  intl: ^0.20.2

  # Google Sign In
  google_sign_in: ^6.2.1

  # Íconos
  cupertino_icons: ^1.0.8
  share_plus: ^12.0.2
  flutter_stripe: ^11.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Playfair Display
      fonts:
        - asset: assets/fonts/PlayfairDisplay-Regular.ttf
        - asset: assets/fonts/PlayfairDisplay-Bold.ttf
          weight: 700