sonar.organization=ennimex
sonar.sources=lib
sonar.tests=test,integration_test
sonar.test.inclusions=**/*_test.dart
sonar.exclusions=**/*.g.dart,**/*.freezed.dart
sonar.dart.lcov.reportPaths=coverage/lcov.info
